[package]
name = "btreemap-core"
version = "0.1.0"
edition = "2021"
description = "Core BTreeMap implementation for high-performance order book management"
license = "MIT"
authors = ["OrderFlow Trading"]

[dependencies]
serde = { version = "1.0", features = ["derive"] }
lazy_static = "1.4"