// src/core/constants.ts

// General Numbers
export const HISTORICAL_CACHE_SIZE = 25000;

// Common Time Intervals (milliseconds)
export const ONE_MINUTE_MS = 60000;
export const FIVE_MINUTES_MS = 300000;
export const FIFTEEN_MINUTES_MS = 900000;
export const THIRTY_MINUTES_MS = 1800000;
export const ONE_HOUR_MS = 3600000;
export const TWO_HOURS_MS = 7200000;
export const ONE_DAY_MS = 86400000;
export const ONE_WEEK_MS = 604800000;

// Common Percentages
export const PERCENT_1 = 0.01;
export const PERCENT_2 = 0.02;
export const PERCENT_5 = 0.05;
export const PERCENT_10 = 0.1;
export const PERCENT_15 = 0.15;
export const PERCENT_20 = 0.2;
export const PERCENT_25 = 0.25;
export const PERCENT_30 = 0.3;
export const PERCENT_40 = 0.4;
export const PERCENT_50 = 0.5;
export const PERCENT_60 = 0.6;
export const PERCENT_80 = 0.8;
export const PERCENT_85 = 0.85;
export const PERCENT_90 = 0.9;
export const PERCENT_95 = 0.95;
export const PERCENT_98 = 0.98;
export const PERCENT_99 = 0.99;

// Common Thresholds
export const VOLUME_THRESHOLD_25 = 25;
export const VOLUME_THRESHOLD_100K = 100000;
export const VOLUME_THRESHOLD_1M = 1000000;
export const MAX_SAFE_INTEGER = 9007199254740991n;

// WebSocket Codes
export const WS_CLOSE_GOING_AWAY = 1001;

// Universal Zone Schema Constants
export const UZ_MAX_ACTIVE_ZONES_MIN = 1;
export const UZ_MAX_ACTIVE_ZONES_MAX = 100;
export const UZ_ZONE_TIMEOUT_MS_MIN = 60000; // 1m
export const UZ_ZONE_TIMEOUT_MS_MAX = 7200000; // 2h
export const UZ_MIN_ZONE_VOLUME_MIN = 1;
export const UZ_MIN_ZONE_VOLUME_MAX = 100000;
export const UZ_MAX_ZONE_WIDTH_MIN = 0.001; // 0.1%
export const UZ_MAX_ZONE_WIDTH_MAX = 0.1; // 10%
export const UZ_MIN_ZONE_STRENGTH_MIN = 0.1; // 10%
export const UZ_MIN_ZONE_STRENGTH_MAX = 1.0; // 100%
export const UZ_COMPLETION_THRESHOLD_MIN = 0.5; // 50%
export const UZ_COMPLETION_THRESHOLD_MAX = 1.0; // 100%
export const UZ_STRENGTH_CHANGE_THRESHOLD_MIN = 0.05; // 5%
export const UZ_STRENGTH_CHANGE_THRESHOLD_MAX = 0.5; // 50%
export const UZ_MIN_CANDIDATE_DURATION_MIN = 60000; // 1m
export const UZ_MIN_CANDIDATE_DURATION_MAX = 1800000; // 30m
export const UZ_MAX_PRICE_DEVIATION_MIN = 0.005; // 0.5%
export const UZ_MAX_PRICE_DEVIATION_MAX = 0.05; // 5%
export const UZ_MIN_TRADE_COUNT_MIN = 5;
export const UZ_MIN_TRADE_COUNT_MAX = 200;
export const UZ_MIN_BUY_RATIO_MIN = 0.5; // 50%
export const UZ_MIN_BUY_RATIO_MAX = 0.8; // 80%
export const UZ_MIN_SELL_RATIO_MIN = 0.5; // 50%
export const UZ_MIN_SELL_RATIO_MAX = 0.8; // 80%
export const UZ_PRICE_STABILITY_THRESHOLD_MIN = 0.8; // 80%
export const UZ_PRICE_STABILITY_THRESHOLD_MAX = 0.99; // 99%
export const UZ_STRONG_ZONE_THRESHOLD_MIN = 0.6; // 60%
export const UZ_STRONG_ZONE_THRESHOLD_MAX = 0.9; // 90%
export const UZ_WEAK_ZONE_THRESHOLD_MIN = 0.2; // 20%
export const UZ_WEAK_ZONE_THRESHOLD_MAX = 0.6; // 60%
export const UZ_MIN_ZONE_CONFLUENCE_COUNT_MIN = 1;
export const UZ_MIN_ZONE_CONFLUENCE_COUNT_MAX = 3;
export const UZ_MAX_ZONE_CONFLUENCE_DISTANCE_MIN = 1;
export const UZ_MAX_ZONE_CONFLUENCE_DISTANCE_MAX = 10;
export const UZ_CONFLUENCE_CONFIDENCE_BOOST_MIN = 0.05; // 5%
export const UZ_CONFLUENCE_CONFIDENCE_BOOST_MAX = 0.3; // 30%
export const UZ_CROSS_TIMEFRAME_BOOST_MIN = 0.05; // 5%
export const UZ_CROSS_TIMEFRAME_BOOST_MAX = 0.25; // 25%

// Standard Zone Config Schema Constants
export const SZC_ZONE_TICKS_MIN = 1;
export const SZC_ZONE_TICKS_MAX = 50;
export const SZC_TIME_WINDOWS_MIN = 60000;
export const SZC_TIME_WINDOWS_MAX = 7200000;
export const SZC_VOLUME_THRESHOLDS_AGGRESSIVE_MIN = 1.0;
export const SZC_VOLUME_THRESHOLDS_AGGRESSIVE_MAX = 1000.0;
export const SZC_VOLUME_THRESHOLDS_PASSIVE_MIN = 0.5;
export const SZC_VOLUME_THRESHOLDS_PASSIVE_MAX = 500.0;
export const SZC_VOLUME_THRESHOLDS_INSTITUTIONAL_MIN = 10.0;
export const SZC_VOLUME_THRESHOLDS_INSTITUTIONAL_MAX = 5000.0;
export const SZC_PRICE_THRESHOLDS_TICK_VALUE_MIN = 0.0001;
export const SZC_PRICE_THRESHOLDS_TICK_VALUE_MAX = 1.0;
export const SZC_PRICE_THRESHOLDS_MIN_ZONE_WIDTH_MIN = 0.001;
export const SZC_PRICE_THRESHOLDS_MIN_ZONE_WIDTH_MAX = 0.1;
export const SZC_PRICE_THRESHOLDS_MAX_ZONE_WIDTH_MIN = 0.01;
export const SZC_PRICE_THRESHOLDS_MAX_ZONE_WIDTH_MAX = 1.0;
export const SZC_PERFORMANCE_CONFIG_MAX_ZONE_HISTORY_MIN = 100;
export const SZC_PERFORMANCE_CONFIG_MAX_ZONE_HISTORY_MAX = 10000;
export const SZC_PERFORMANCE_CONFIG_CLEANUP_INTERVAL_MIN = 300000;
export const SZC_PERFORMANCE_CONFIG_CLEANUP_INTERVAL_MAX = 7200000;
export const SZC_PERFORMANCE_CONFIG_MAX_MEMORY_MB_MIN = 10;
export const SZC_PERFORMANCE_CONFIG_MAX_MEMORY_MB_MAX = 500;

// Exhaustion Detector Schema Constants
export const ED_TIME_WINDOW_INDEX_MIN = 0;
export const ED_TIME_WINDOW_INDEX_MAX = 5;
export const ED_EXHAUSTION_THRESHOLD_MIN = 0.01;
export const ED_EXHAUSTION_THRESHOLD_MAX = 1.0;
export const ED_EVENT_COOLDOWN_MS_MIN = 1000;
export const ED_EVENT_COOLDOWN_MS_MAX = 300000;
export const ED_MAX_ZONES_PER_SIDE_MIN = 1;
export const ED_MAX_ZONES_PER_SIDE_MAX = 20;
export const ED_ZONE_DEPLETION_THRESHOLD_MIN = 0.1;
export const ED_ZONE_DEPLETION_THRESHOLD_MAX = 0.95;
export const ED_GAP_DETECTION_TICKS_MIN = 1;
export const ED_GAP_DETECTION_TICKS_MAX = 10;
export const ED_ZONE_HISTORY_WINDOW_MS_MIN = 5000;
export const ED_ZONE_HISTORY_WINDOW_MS_MAX = 300000;
export const ED_PASSIVE_RATIO_BALANCE_THRESHOLD_MIN = 0.3;
export const ED_PASSIVE_RATIO_BALANCE_THRESHOLD_MAX = 0.99;
export const ED_PASSIVE_RATIO_ANOMALY_STD_DEV_MIN = 1.0;
export const ED_PASSIVE_RATIO_ANOMALY_STD_DEV_MAX = 10.0;
export const ED_MIN_PEAK_VOLUME_MIN = 10;
export const ED_MIN_PEAK_VOLUME_MAX = 100000;
export const ED_CV_MAX_REASONABLE_VELOCITY_MIN = 1;
export const ED_CV_MAX_REASONABLE_VELOCITY_MAX = 10000;
export const ED_CV_MIN_CONSUMPTION_CONFIDENCE_MIN = 0.1;
export const ED_CV_MIN_CONSUMPTION_CONFIDENCE_MAX = 1.0;
export const ED_CV_CONFIDENCE_DECAY_TIME_MS_MIN = 1000;
export const ED_CV_CONFIDENCE_DECAY_TIME_MS_MAX = 300000;
export const ED_CV_MIN_AGGRESSIVE_VOLUME_MIN = 1;
export const ED_CV_MIN_AGGRESSIVE_VOLUME_MAX = 1000;

// Absorption Detector Schema Constants
export const AD_MIN_AGG_VOLUME_MIN = 1;
export const AD_MIN_AGG_VOLUME_MAX = 100000;
export const AD_TIME_WINDOW_INDEX_MIN = 0;
export const AD_TIME_WINDOW_INDEX_MAX = 5;
export const AD_EVENT_COOLDOWN_MS_MIN = 1000;
export const AD_EVENT_COOLDOWN_MS_MAX = 60000;
export const AD_PRICE_EFFICIENCY_THRESHOLD_MIN = 0.0001;
export const AD_PRICE_EFFICIENCY_THRESHOLD_MAX = 0.1;
export const AD_MAX_PRICE_IMPACT_RATIO_MIN = 0.0;
export const AD_MAX_PRICE_IMPACT_RATIO_MAX = 1.0;
export const AD_MIN_PASSIVE_MULTIPLIER_MIN = 0.5;
export const AD_MIN_PASSIVE_MULTIPLIER_MAX = 250.0;
export const AD_PASSIVE_ABSORPTION_THRESHOLD_MIN = 0.1;
export const AD_PASSIVE_ABSORPTION_THRESHOLD_MAX = 1.0;
export const AD_PASSIVE_ABSORPTION_THRESHOLD_ELITE_MIN = 0.98;
export const AD_PASSIVE_ABSORPTION_THRESHOLD_ELITE_MAX = 1.0;
export const AD_ROLLING_WINDOW_SIZE_MIN = 10;
export const AD_ROLLING_WINDOW_SIZE_MAX = 5000;
export const AD_EXPECTED_MOVEMENT_SCALING_FACTOR_MIN = 1;
export const AD_EXPECTED_MOVEMENT_SCALING_FACTOR_MAX = 100;
export const AD_MAX_ZONE_COUNT_FOR_SCORING_MIN = 1;
export const AD_MAX_ZONE_COUNT_FOR_SCORING_MAX = 10;
export const AD_BALANCE_THRESHOLD_MIN = 0.0001;
export const AD_BALANCE_THRESHOLD_MAX = 0.25;
export const AD_MAX_VOLUME_MULTIPLIER_RATIO_MIN = 1.0;
export const AD_MAX_VOLUME_MULTIPLIER_RATIO_MAX = 50.0;
export const AD_MAX_ZONES_PER_SIDE_MIN = 3;
export const AD_MAX_ZONES_PER_SIDE_MAX = 20;
export const AD_ZONE_HISTORY_WINDOW_MS_MIN = 30000;
export const AD_ZONE_HISTORY_WINDOW_MS_MAX = 300000;
export const AD_ABSORPTION_ZONE_THRESHOLD_MIN = 1.2;
export const AD_ABSORPTION_ZONE_THRESHOLD_MAX = 3.0;
export const AD_MIN_PASSIVE_VOLUME_FOR_ZONE_MIN = 10;
export const AD_MIN_PASSIVE_VOLUME_FOR_ZONE_MAX = 10000;
export const AD_PRICE_STABILITY_TICKS_MIN = 1;
export const AD_PRICE_STABILITY_TICKS_MAX = 5;
export const AD_MIN_ABSORPTION_EVENTS_MIN = 1;
export const AD_MIN_ABSORPTION_EVENTS_MAX = 10;

// Delta CVD Detector Schema Constants
export const DCD_SIGNAL_THRESHOLD_MIN = 0.01;
export const DCD_SIGNAL_THRESHOLD_MAX = 8.0;
export const DCD_EVENT_COOLDOWN_MS_MIN = 1000;
export const DCD_EVENT_COOLDOWN_MS_MAX = 1800000;
export const DCD_TIME_WINDOW_INDEX_MIN = 0;
export const DCD_TIME_WINDOW_INDEX_MAX = 5;
export const DCD_CVD_IMBALANCE_THRESHOLD_MIN = 0.5;
export const DCD_CVD_IMBALANCE_THRESHOLD_MAX = 1.0;
export const DCD_INSTITUTIONAL_THRESHOLD_MIN = 5;
export const DCD_INSTITUTIONAL_THRESHOLD_MAX = 5000.0;
export const DCD_VOLUME_EFFICIENCY_THRESHOLD_MIN = 0.1;
export const DCD_VOLUME_EFFICIENCY_THRESHOLD_MAX = 0.75;
export const DCD_ZONE_SEARCH_DISTANCE_MIN = 5;
export const DCD_ZONE_SEARCH_DISTANCE_MAX = 50;
export const DCD_TRADE_RATE_WINDOW_SIZE_MIN = 10;
export const DCD_TRADE_RATE_WINDOW_SIZE_MAX = 5000;
export const DCD_VOLUME_RATE_WINDOW_SIZE_MIN = 10;
export const DCD_VOLUME_RATE_WINDOW_SIZE_MAX = 5000;

// Accumulation Detector Schema Constants
export const ACD_EVENT_COOLDOWN_MS_MIN = 1000;
export const ACD_EVENT_COOLDOWN_MS_MAX = 60000;
export const ACD_CONFIDENCE_THRESHOLD_MIN = 0.1;
export const ACD_CONFIDENCE_THRESHOLD_MAX = 0.9;
export const ACD_CONFLUENCE_MIN_ZONES_MIN = 1;
export const ACD_CONFLUENCE_MIN_ZONES_MAX = 10;
export const ACD_CONFLUENCE_MAX_DISTANCE_MIN = 0.01;
export const ACD_CONFLUENCE_MAX_DISTANCE_MAX = 1.0;
export const ACD_CONFLUENCE_CONFIDENCE_BOOST_MIN = 0.05;
export const ACD_CONFLUENCE_CONFIDENCE_BOOST_MAX = 0.3;
export const ACD_CROSS_TIMEFRAME_CONFIDENCE_BOOST_MIN = 0.05;
export const ACD_CROSS_TIMEFRAME_CONFIDENCE_BOOST_MAX = 0.3;
export const ACD_ACCUMULATION_VOLUME_THRESHOLD_MIN = 1;
export const ACD_ACCUMULATION_VOLUME_THRESHOLD_MAX = 1000;
export const ACD_ACCUMULATION_RATIO_THRESHOLD_MIN = 0.3;
export const ACD_ACCUMULATION_RATIO_THRESHOLD_MAX = 0.9;
export const ACD_ALIGNMENT_SCORE_THRESHOLD_MIN = 0.3;
export const ACD_ALIGNMENT_SCORE_THRESHOLD_MAX = 0.8;
export const ACD_DEFAULT_DURATION_MS_MIN = 30000;
export const ACD_DEFAULT_DURATION_MS_MAX = 600000;
export const ACD_MAX_PRICE_SUPPORT_MIN = 0.5;
export const ACD_MAX_PRICE_SUPPORT_MAX = 5.0;
export const ACD_PRICE_SUPPORT_MULTIPLIER_MIN = 1.0;
export const ACD_PRICE_SUPPORT_MULTIPLIER_MAX = 10.0;
export const ACD_MIN_PASSIVE_VOLUME_FOR_EFFICIENCY_MIN = 1;
export const ACD_MIN_PASSIVE_VOLUME_FOR_EFFICIENCY_MAX = 100;
export const ACD_DEFAULT_VOLATILITY_MIN = 0.01;
export const ACD_DEFAULT_VOLATILITY_MAX = 0.5;
export const ACD_DEFAULT_BASELINE_VOLATILITY_MIN = 0.01;
export const ACD_DEFAULT_BASELINE_VOLATILITY_MAX = 0.3;
export const ACD_CONFLUENCE_STRENGTH_DIVISOR_MIN = 1;
export const ACD_CONFLUENCE_STRENGTH_DIVISOR_MAX = 10;
export const ACD_PASSIVE_TO_AGGRESSIVE_RATIO_MIN = 0.3;
export const ACD_PASSIVE_TO_AGGRESSIVE_RATIO_MAX = 2.0;

// Distribution Detector Schema Constants
export const DD_EVENT_COOLDOWN_MS_MIN = 1000;
export const DD_EVENT_COOLDOWN_MS_MAX = 60000;
export const DD_CONFIDENCE_THRESHOLD_MIN = 0.1;
export const DD_CONFIDENCE_THRESHOLD_MAX = 0.9;
export const DD_CONFLUENCE_MIN_ZONES_MIN = 1;
export const DD_CONFLUENCE_MIN_ZONES_MAX = 10;
export const DD_CONFLUENCE_MAX_DISTANCE_MIN = 0.01;
export const DD_CONFLUENCE_MAX_DISTANCE_MAX = 1.0;
export const DD_CONFLUENCE_CONFIDENCE_BOOST_MIN = 0.05;
export const DD_CONFLUENCE_CONFIDENCE_BOOST_MAX = 0.3;
export const DD_CROSS_TIMEFRAME_CONFIDENCE_BOOST_MIN = 0.05;
export const DD_CROSS_TIMEFRAME_CONFIDENCE_BOOST_MAX = 0.3;
export const DD_DISTRIBUTION_VOLUME_THRESHOLD_MIN = 1;
export const DD_DISTRIBUTION_VOLUME_THRESHOLD_MAX = 1000;
export const DD_DISTRIBUTION_RATIO_THRESHOLD_MIN = 0.3;
export const DD_DISTRIBUTION_RATIO_THRESHOLD_MAX = 0.9;
export const DD_ALIGNMENT_SCORE_THRESHOLD_MIN = 0.3;
export const DD_ALIGNMENT_SCORE_THRESHOLD_MAX = 0.8;
export const DD_DEFAULT_DURATION_MS_MIN = 30000;
export const DD_DEFAULT_DURATION_MS_MAX = 600000;
export const DD_MAX_PRICE_RESISTANCE_MIN = 0.5;
export const DD_MAX_PRICE_RESISTANCE_MAX = 5.0;
export const DD_PRICE_RESISTANCE_MULTIPLIER_MIN = 1.0;
export const DD_PRICE_RESISTANCE_MULTIPLIER_MAX = 10.0;
export const DD_MIN_PASSIVE_VOLUME_FOR_EFFICIENCY_MIN = 1;
export const DD_MIN_PASSIVE_VOLUME_FOR_EFFICIENCY_MAX = 100;
export const DD_DEFAULT_VOLATILITY_MIN = 0.01;
export const DD_DEFAULT_VOLATILITY_MAX = 0.5;
export const DD_DEFAULT_BASELINE_VOLATILITY_MIN = 0.01;
export const DD_DEFAULT_BASELINE_VOLATILITY_MAX = 0.3;

// Simple Iceberg Detector Schema Constants
export const SID_MIN_ORDER_COUNT_MIN = 2;
export const SID_MIN_ORDER_COUNT_MAX = 1000;
export const SID_MIN_TOTAL_SIZE_MIN = 10;
export const SID_MIN_TOTAL_SIZE_MAX = 100000000;
export const SID_TIME_WINDOW_INDEX_MIN = 0;
export const SID_TIME_WINDOW_INDEX_MAX = 5;
export const SID_MAX_ORDER_GAP_MS_MIN = 100;
export const SID_MAX_ORDER_GAP_MS_MAX = 3600000;
export const SID_MAX_ACTIVE_PATTERNS_MIN = 5;
export const SID_MAX_ACTIVE_PATTERNS_MAX = 10000;
export const SID_MAX_RECENT_TRADES_MIN = 10;
export const SID_MAX_RECENT_TRADES_MAX = 10000;

// Traditional Indicators Schema Constants
export const TI_TIMEFRAME_MS_MIN = 60000;
export const TI_TIMEFRAME_MS_MAX = 3600000;
export const TI_VWAP_WINDOW_MS_MIN = 60000;
export const TI_VWAP_WINDOW_MS_MAX = 7200000;
export const TI_VWAP_MAX_DEVIATION_PERCENT_MIN = 0.1;
export const TI_VWAP_MAX_DEVIATION_PERCENT_MAX = 10.0;
export const TI_VWAP_MIN_DEVIATION_PERCENT_MIN = 0.01;
export const TI_VWAP_MIN_DEVIATION_PERCENT_MAX = 5.0;
export const TI_VWAP_WEIGHT_DECAY_MIN = 0.8;
export const TI_VWAP_WEIGHT_DECAY_MAX = 0.99;
export const TI_RSI_PERIOD_MIN = 5;
export const TI_RSI_PERIOD_MAX = 50;
export const TI_RSI_TIMEFRAME_MS_MIN = 60000;
export const TI_RSI_TIMEFRAME_MS_MAX = 3600000;
export const TI_RSI_OVERBOUGHT_THRESHOLD_MIN = 60;
export const TI_RSI_OVERBOUGHT_THRESHOLD_MAX = 90;
export const TI_RSI_OVERSOLD_THRESHOLD_MIN = 10;
export const TI_RSI_OVERSOLD_THRESHOLD_MAX = 40;
export const TI_RSI_EXTREME_OVERBOUGHT_MIN = 75;
export const TI_RSI_EXTREME_OVERBOUGHT_MAX = 95;
export const TI_RSI_EXTREME_OVERSOLD_MIN = 5;
export const TI_RSI_EXTREME_OVERSOLD_MAX = 25;
export const TI_OIR_WINDOW_MS_MIN = 60000;
export const TI_OIR_WINDOW_MS_MAX = 1800000;
export const TI_OIR_BUY_DOMINANCE_THRESHOLD_MIN = 0.5;
export const TI_OIR_BUY_DOMINANCE_THRESHOLD_MAX = 0.9;
export const TI_OIR_SELL_DOMINANCE_THRESHOLD_MIN = 0.1;
export const TI_OIR_SELL_DOMINANCE_THRESHOLD_MAX = 0.5;
export const TI_OIR_NEUTRAL_ZONE_MIN = 0.05;
export const TI_OIR_NEUTRAL_ZONE_MAX = 0.3;
export const TI_OIR_MIN_VOLUME_THRESHOLD_MIN = 1;
export const TI_OIR_MIN_VOLUME_THRESHOLD_MAX = 1000;
export const TI_FS_VWAP_WEIGHT_MIN = 0;
export const TI_FS_VWAP_WEIGHT_MAX = 3.0;
export const TI_FS_RSI_WEIGHT_MIN = 0;
export const TI_FS_RSI_WEIGHT_MAX = 3.0;
export const TI_FS_OIR_WEIGHT_MIN = 0;
export const TI_FS_OIR_WEIGHT_MAX = 3.0;
export const TI_FS_WEIGHT_MIN = 0;

// Microstructure Analyzer Schema Constants
export const MA_BURST_THRESHOLD_MS_MIN = 10;
export const MA_BURST_THRESHOLD_MS_MAX = 1000;
export const MA_UNIFORMITY_THRESHOLD_MIN = 0.1;
export const MA_UNIFORMITY_THRESHOLD_MAX = 0.5;
export const MA_SIZING_CONSISTENCY_THRESHOLD_MIN = 0.05;
export const MA_SIZING_CONSISTENCY_THRESHOLD_MAX = 0.3;
export const MA_PERSISTENCE_WINDOW_SIZE_MIN = 3;
export const MA_PERSISTENCE_WINDOW_SIZE_MAX = 20;
export const MA_MARKET_MAKING_SPREAD_THRESHOLD_MIN = 0.001;
export const MA_MARKET_MAKING_SPREAD_THRESHOLD_MAX = 0.1;
export const MA_ICEBERG_SIZE_RATIO_MIN = 0.5;
export const MA_ICEBERG_SIZE_RATIO_MAX = 0.95;
export const MA_ARBITRAGE_TIME_THRESHOLD_MIN = 10;
export const MA_ARBITRAGE_TIME_THRESHOLD_MAX = 500;

// Individual Trades Manager Schema Constants
export const ITM_CRITERIA_MIN_ORDER_SIZE_PERCENTILE_MIN = 50;
export const ITM_CRITERIA_MIN_ORDER_SIZE_PERCENTILE_MAX = 99;
export const ITM_CACHE_MAX_SIZE_MIN = 1000;
export const ITM_CACHE_MAX_SIZE_MAX = 100000;
export const ITM_CACHE_TTL_MS_MIN = 60000;
export const ITM_CACHE_TTL_MS_MAX = 3600000;
export const ITM_RATE_LIMIT_MAX_REQUESTS_PER_SECOND_MIN = 1;
export const ITM_RATE_LIMIT_MAX_REQUESTS_PER_SECOND_MAX = 10;
export const ITM_RATE_LIMIT_BATCH_SIZE_MIN = 10;
export const ITM_RATE_LIMIT_BATCH_SIZE_MAX = 1000;

// Signal Manager Schema Constants
export const SM_PRICE_TOLERANCE_PERCENT_MIN = 0.01;
export const SM_PRICE_TOLERANCE_PERCENT_MAX = 10.0;
export const SM_SIGNAL_THROTTLE_MS_MIN = 1000;
export const SM_SIGNAL_THROTTLE_MS_MAX = 60000;
export const SM_CORRELATION_WINDOW_MS_MIN = 60000;
export const SM_CORRELATION_WINDOW_MS_MAX = 3600000;
export const SM_MAX_HISTORY_SIZE_MIN = 10;
export const SM_MAX_HISTORY_SIZE_MAX = 1000;
export const SM_DEFAULT_PRIORITY_MIN = 1;
export const SM_DEFAULT_PRIORITY_MAX = 10;
export const SM_VOLATILITY_HIGH_THRESHOLD_MIN = 0.01;
export const SM_VOLATILITY_HIGH_THRESHOLD_MAX = 0.5;
export const SM_VOLATILITY_LOW_THRESHOLD_MIN = 0.001;
export const SM_VOLATILITY_LOW_THRESHOLD_MAX = 0.1;
export const SM_DEFAULT_LOW_VOLATILITY_MIN = 0.001;
export const SM_DEFAULT_LOW_VOLATILITY_MAX = 0.1;
export const SM_DEFAULT_VOLATILITY_ERROR_MIN = 0.01;
export const SM_DEFAULT_VOLATILITY_ERROR_MAX = 0.2;
export const SM_PRIORITY_QUEUE_HIGH_THRESHOLD_MIN = 5.0;
export const SM_PRIORITY_QUEUE_HIGH_THRESHOLD_MAX = 10.0;
export const SM_BACKPRESSURE_YIELD_MS_MIN = 1;
export const SM_BACKPRESSURE_YIELD_MS_MAX = 100;
export const SM_MARKET_VOLATILITY_WEIGHT_MIN = 0.1;
export const SM_MARKET_VOLATILITY_WEIGHT_MAX = 1.0;
export const SM_RSI_UPDATE_FREQUENCY_MIN = 1;
export const SM_RSI_UPDATE_FREQUENCY_MAX = 100;
export const SM_MAX_RSI_BACKLOG_SIZE_MIN = 1000;
export const SM_MAX_RSI_BACKLOG_SIZE_MAX = 100000;
export const SM_MAX_SIGNAL_BACKLOG_AGE_MINUTES_MIN = 10;
export const SM_MAX_SIGNAL_BACKLOG_AGE_MINUTES_MAX = 480;
export const SM_ACCUMULATION_DETECTOR_PRIORITY_MIN = 1;
export const SM_ACCUMULATION_DETECTOR_PRIORITY_MAX = 100;
export const SM_DISTRIBUTION_DETECTOR_PRIORITY_MIN = 1;
export const SM_DISTRIBUTION_DETECTOR_PRIORITY_MAX = 100;

// Anomaly Detector Schema Constants
export const ANOMALY_DETECTOR_MIN_HISTORY_MIN = 2;

// Config Constants
export const HTTP_PORT_MIN = 1;
export const HTTP_PORT_MAX = 65535;
export const WS_PORT_MIN = 1;
export const WS_PORT_MAX = 65535;
export const HTTP_NOT_FOUND = 404;
